//! Core domain types for the data-fabrication challenge.
//!
//! Miners submit Python harnesses that generate conversation datasets.
//! These types define the submission format and generated dataset structure.

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};

#[cfg(feature = "std")]
pub mod error;

#[cfg(feature = "std")]
pub mod sandbox;

#[cfg(feature = "std")]
pub mod ast_validation;

#[cfg(feature = "std")]
pub mod ast_similarity;

#[cfg(all(feature = "std", unix))]
pub mod resource_limits;

#[cfg(feature = "std")]
pub mod llm_client;

#[cfg(feature = "std")]
pub mod consensus;

#[cfg(feature = "std")]
pub mod cache;

pub mod config;
pub mod schema;
pub mod scoring_types;

#[cfg(feature = "std")]
pub use error::{DataFabricationError, Result};

#[cfg(feature = "std")]
pub use llm_client::{LlmClient, MockLlmClient, WasmLlmClient};

#[cfg(feature = "http-client")]
pub use llm_client::HttpLlmClient;

#[cfg(feature = "std")]
pub use sandbox::{Sandbox, SandboxConfig, SandboxResult, HARNESS_FILENAME, OUTPUT_FILENAME};

#[cfg(all(feature = "std", unix))]
pub use resource_limits::{
    ResourceLimitError, ResourceLimits, DEFAULT_FILE_SIZE_BYTES, DEFAULT_MEMORY_BYTES,
    MAX_CPU_TIME_SECONDS, MAX_FILE_SIZE_BYTES, MAX_MEMORY_BYTES, MAX_PROCESSES,
};

#[cfg(feature = "std")]
pub use ast_validation::{validate_python_code, SecurityViolation, Severity};

#[cfg(feature = "std")]
pub use ast_similarity::{
    normalize_ast, hash_structure, compare_structures, check_plagiarism,
    SimilarityScore, ComparisonResult, PlagiarismStatus, NormalizedAst,
    StructureHash, PlagiarismReport, SubmissionCluster, SimilarityError,
};

pub use config::{
    ConfigError, EvaluationConfig, HarnessExecutionConfig, DEFAULT_MEMORY_LIMIT_BYTES,
    MAX_CONVERSATION_COUNT, MAX_DATASET_SIZE_BYTES, MAX_TIMEOUT_SECONDS, MIN_CONVERSATION_COUNT,
};
pub use schema::{JsonlParser, SchemaError};
pub use scoring_types::{
    validate_score, ConversationScore, CriteriaScores, DatasetScore, LlmEvaluationScore, ScoreError,
};

#[cfg(feature = "std")]
pub use consensus::{ConsensusResult, consensus};

#[cfg(feature = "std")]
pub use cache::{EvaluationCache, hash_conversation, DEFAULT_TTL};

#[cfg(feature = "std")]
extern crate std;

/// A miner's submission containing a Python harness for dataset generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HarnessSubmission {
    pub hotkey: String,
    pub epoch: u64,
    pub code_hash: String,
    pub package: Vec<u8>,
}

/// A dataset generated by running a Python harness.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedDataset {
    pub conversations: Vec<ConversationEntry>,
    pub metadata: DatasetMetadata,
    pub generation_time_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatasetMetadata {
    pub conversation_count: u64,
    pub total_messages: u64,
    pub size_bytes: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation_params: Option<GenerationParams>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerationParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationEntry {
    pub messages: Vec<Message>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_calls: Option<Vec<FunctionCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub role: String,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_harness_submission_serialization() {
        let submission = HarnessSubmission {
            hotkey: "5GrwvaEF5zXD".to_string(),
            epoch: 42,
            code_hash: "abc123".to_string(),
            package: vec![1, 2, 3],
        };
        let json = serde_json::to_string(&submission).unwrap();
        let deserialized: HarnessSubmission = serde_json::from_str(&json).unwrap();
        assert_eq!(submission.hotkey, deserialized.hotkey);
    }
}
